import PersonalInfo from '@/components/personalinfo/PersonalInfo'
import Skills from '@/components/skills/Skills'
import SocialNetworks from '@/components/socialNetworks/SocialNetworks'
import Head from 'next/head'
import Title from "../components/title/Title"
import Proyect from '@/components/proyects/Project'




export default function Home() {
  return (
    <>
      <Head>
        <title>Mariano Langge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <SocialNetworks />
      <Title />

      <div className="container mx-auto">
        <PersonalInfo />
        <Skills />
        <Proyect />
      </div>





    </>
  )
}
